// throwing and catching err in js

try{
    const name = Dhruv
    const ans = name.length;
    console.log(ans) 
}
 catch(e){
    console.log("hi from catch");   
}

console.log("hi");
